---
all:
  children:
    portfolio_servers:
      hosts:
        portfolio_prod_new:
          ansible_host: 213.239.141.25
          ansible_user: ubuntu
          server_name: portfolio-prod-new
          server_location: HETZNER
