---
all:
  children:
    portfolio_servers:
      hosts:
        portfolio_prod_new:
          ansible_host: 34.38.146.8
          ansible_user: nikhil
          ansible_ssh_private_key_file: ~/.ssh/google_compute_engine
          ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
          server_name: portfolio-prod-new
          server_location: GCP
