all:
  children:
    portfolio_servers:
      hosts:
        portfolio_prod:
          ansible_host: 207.148.27.173
          ansible_user: root
          server_location: VULTR
          server_name: portfolio-prod-1

