name: portfolio
region: nyc
services:
  - name: web
    github:
      repo: niks3089/portfolio
      branch: main
      deploy_on_push: true
    build_command: npm install
    run_command: npm start
    http_port: 3000
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET

